#+TITLE: Pelasgian Software License, Version 1.0
#+SUBTITLE: Public Profile
#+AUTHOR: D.A.Pelasgus
** Abbreviation
PSL

** Notice
Copyright ${year} ${licensor name}

** Terms and Conditions
*** Licensor ("The Pelasgus Group")
The entity providing the Software under these Terms and Conditions.

*** The Software
The "Software" refers to each version of the software made available by the Pelasgus Group under these Terms and Conditions, as evidenced by the inclusion of these Terms and Conditions with the Software.

*** Licence Grant
Subject to your compliance with this Licence Grant and the Patents, Redistribution, and Trademark clauses below, the Pelasgus Group hereby grants you the right to use, copy, modify, create derivative works, publicly perform, publicly display, and redistribute the Software for any Permitted Purpose identified below.

*** Permitted Purpose
A Permitted Purpose is any purpose other than a Competing Use. A Competing Use refers to making the Software available to others in a commercial product or service that:
1. Substitutes for the Software;
2. Substitutes for any other product or service offered by the Pelasgus Group using the Software that exists as of the date the Software is made available; or
3. Offers the same or substantially similar functionality as the Software.

Permitted Purposes specifically include using the Software:
1. For your internal use and access;
2. For non-commercial educational purposes;
3. For non-commercial research; and
4. In connection with professional services that you provide to a licensee using the Software in accordance with these Terms and Conditions.

*** Patents
To the extent your use for a Permitted Purpose would necessarily infringe the patents held by the Pelasgus Group, the licence grant above includes a licence under these patents. If you make a claim against any party that the Software infringes or contributes to the infringement of any patent, your patent licence to the Software terminates immediately.

*** Redistribution
These Terms and Conditions apply to all copies, modifications, and derivatives of the Software.
If you redistribute any copies, modifications, or derivatives of the Software, you must include a copy of or a link to these Terms and Conditions and not remove any copyright notices provided in or with the Software.

*** Disclaimer
THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, TITLE, OR NON-INFRINGEMENT.
IN NO EVENT SHALL THE PELASGUS GROUP BE LIABLE TO YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THE SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE.

*** Trademarks
Except for displaying the Licence Details and identifying the Pelasgus Group as the origin of the Software, you have no rights under these Terms and Conditions to use the trademarks, trade names, service marks, or product names of the Pelasgus Group.

** Grant of Future Licence
The Pelasgus Group hereby irrevocably grants you an additional licence to use the Software under the latest version of the GPL licence, effective on the second anniversary of the date the Software is made available. On or after that date, you may use the Software under the latest version of the GPL licence, in which case the following will apply:
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
